# Installing Jenkins using docker-compose.yaml
# --detach
name: tax-management-system
services:
    myjenkins-blueocean:
        container_name: jenkins-blueocean
        restart: on-failure
        networks:
            - jenkins
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
        ports:
            - 8080:8080
            - 50000:50000
        image: myjenkins-blueocean:2.492.2-1
networks:
    jenkins:
        external: true
        name: jenkins
volumes:
    jenkins-data:
        external: true
        name: jenkins-data
    jenkins-docker-certs:
        external: true
        name: jenkins-docker-certs